# Generated by Django 2.2.6 on 2019-10-29 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=300)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('buying_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('is_ordered', models.BooleanField(default=False)),
            ],
        ),
    ]
